name: Build all driver samples
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        platform: [x64,ARM64]
    runs-on: windows-latest
    env:
      Solution_Path: 
                     avstream\avscamera\avscamera.sln
                     avstream\avshws\avshws.sln
                     avstream\avssamp\avssamp.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: |
          msbuild audio\Acx\Samples\udioCodec\Driver\AudioCodec.sln -p:Configuration:${{ env.Configuration }} -p:Platform:${{ env.Platform }}
          msbuild simpleaudiosample\SimpleAudioSample.sln -p:Configuration:${{ env.Configuration }} -p:Platform:${{ env.Platform }}
          msbuild sysvad\sysvad.sln -p:Configuration:${{ env.Configuration }} -p:Platform:${{ env.Platform }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
